version: '3'
services:
    webapp:
        container_name: webbrew
        restart: always
        build: .
        command: bash 'rundocker.sh'
        volumes:
            - .:/brewery
        ports:
            - 5000:5000
        depends_on:
            - db
    db:
        container_name: postgres
        image: postgres
        restart: always
        env_file: .env.docker
        volumes:
            - ./db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
            